// ── APP DATA: CATEGORIES, ANIMATIONS, FALLBACKS, SYLLABLES ─────────────────

const CATS={
  cosas:{label:"Cosas",icon:"🪑",color:"#7B8FF7",items:[
    {es:"Silla",en:"chair",wiki:"Chair"},{es:"Mesa",en:"table",wiki:"Table_(furniture)"},
    {es:"Cama",en:"bed",wiki:"Bed"},{es:"Puerta",en:"door",wiki:"Door"},
    {es:"Ventana",en:"window",wiki:"Window"},{es:"Libro",en:"book",wiki:"Book"},
    {es:"Lápiz",en:"pencil",wiki:"Pencil"},{es:"Zapato",en:"shoe",wiki:"Shoe"},
    {es:"Sombrero",en:"hat",wiki:"Hat"},{es:"Reloj",en:"clock",wiki:"Clock"},
    {es:"Mochila",en:"backpack",wiki:"Backpack"},{es:"Taza",en:"cup",wiki:"Cup"},
    {es:"Cuchara",en:"spoon",wiki:"Spoon"},{es:"Pelota",en:"ball",wiki:"Ball_(object)"},
    {es:"Tijeras",en:"scissors",wiki:"Scissors"},{es:"Teléfono",en:"phone",wiki:"Mobile_phone"},
    {es:"Lámpara",en:"lamp",wiki:"Lamp"},{es:"Espejo",en:"mirror",wiki:"Mirror"},
    {es:"Llave",en:"key",wiki:"Key_(lock)"},{es:"Botella",en:"bottle",wiki:"Bottle"},
    {es:"Globo",en:"balloon",wiki:"Balloon"},{es:"Paraguas",en:"umbrella",wiki:"Umbrella"},
    {es:"Vela",en:"candle",wiki:"Candle"},{es:"Guitarra",en:"guitar",wiki:"Guitar"},
    {es:"Bicicleta",en:"bicycle",wiki:"Bicycle"},{es:"Avión",en:"airplane",wiki:"Airplane"},
    {es:"Tren",en:"train",wiki:"Train"},{es:"Barco",en:"ship",wiki:"Ship"},
    {es:"Cepillo",en:"brush",wiki:"Brush"},{es:"Carro",en:"car",wiki:"Car"}
  ]},
  animales:{label:"Animales",icon:"🐘",color:"#4CAF8A",items:[
    {es:"Perro",en:"dog",wiki:"Dog"},{es:"Gato",en:"cat",wiki:"Cat"},
    {es:"Elefante",en:"elephant",wiki:"Elephant"},{es:"León",en:"lion",wiki:"Lion"},
    {es:"Tigre",en:"tiger",wiki:"Tiger"},{es:"Jirafa",en:"giraffe",wiki:"Giraffe"},
    {es:"Cebra",en:"zebra",wiki:"Zebra"},{es:"Pingüino",en:"penguin",wiki:"Penguin"},
    {es:"Delfín",en:"dolphin",wiki:"Dolphin"},{es:"Águila",en:"eagle",wiki:"Eagle"},
    {es:"Oso",en:"bear",wiki:"Bear"},{es:"Lobo",en:"wolf",wiki:"Wolf"},
    {es:"Zorro",en:"fox",wiki:"Fox"},{es:"Conejo",en:"rabbit",wiki:"Rabbit"},
    {es:"Tortuga",en:"turtle",wiki:"Turtle"},{es:"Cocodrilo",en:"crocodile",wiki:"Crocodile"},
    {es:"Mariposa",en:"butterfly",wiki:"Butterfly"},{es:"Abeja",en:"bee",wiki:"Bee"},
    {es:"Pulpo",en:"octopus",wiki:"Octopus"},{es:"Tiburón",en:"shark",wiki:"Shark"},
    {es:"Caballo",en:"horse",wiki:"Horse"},{es:"Vaca",en:"cow",wiki:"Cattle"},
    {es:"Cerdo",en:"pig",wiki:"Pig"},{es:"Pato",en:"duck",wiki:"Duck"},
    {es:"Gallina",en:"hen",wiki:"Chicken"},{es:"Camello",en:"camel",wiki:"Camel"},
    {es:"Hipopótamo",en:"hippo",wiki:"Hippopotamus"},{es:"Loro",en:"parrot",wiki:"Parrot"},
    {es:"Panda",en:"panda",wiki:"Giant_panda"},{es:"Koala",en:"koala",wiki:"Koala"},
    {es:"Canguro",en:"kangaroo",wiki:"Kangaroo"},{es:"Rana",en:"frog",wiki:"Frog"},
    {es:"Serpiente",en:"snake",wiki:"Snake"},{es:"Búho",en:"owl",wiki:"Owl"},
    {es:"Cangrejo",en:"crab",wiki:"Crab"},{es:"Ballena",en:"whale",wiki:"Whale"},
    {es:"Gorila",en:"gorilla",wiki:"Gorilla"},{es:"Flamenco",en:"flamingo",wiki:"Flamingo"},
    {es:"Colibrí",en:"hummingbird",wiki:"Hummingbird"},{es:"Murciélago",en:"bat",wiki:"Bat"}
  ]},
  cuerpo:{label:"Cuerpo",icon:"👁️",color:"#E8825A",items:[
    {es:"Ojo",en:"eye",wiki:"Eye"},{es:"Nariz",en:"nose",wiki:"Nose"},
    {es:"Boca",en:"mouth",wiki:"Mouth"},{es:"Oreja",en:"ear",wiki:"Ear"},
    {es:"Mano",en:"hand",wiki:"Hand"},{es:"Pie",en:"foot",wiki:"Foot"},
    {es:"Brazo",en:"arm",wiki:"Arm"},{es:"Pierna",en:"leg",wiki:"Leg"},
    {es:"Cabeza",en:"head",wiki:"Head"},{es:"Diente",en:"tooth",wiki:"Tooth"},
    {es:"Cabello",en:"hair",wiki:"Hair"},{es:"Rodilla",en:"knee",wiki:"Knee"},
    {es:"Codo",en:"elbow",wiki:"Elbow"},{es:"Hombro",en:"shoulder",wiki:"Shoulder"},
    {es:"Dedo",en:"finger",wiki:"Finger"},{es:"Uña",en:"nail",wiki:"Nail_(anatomy)"},
    {es:"Espalda",en:"back",wiki:"Human_back"},{es:"Cuello",en:"neck",wiki:"Neck"},
    {es:"Mejilla",en:"cheek",wiki:"Cheek"},{es:"Frente",en:"forehead",wiki:"Forehead"}
  ]},
  frutas:{label:"Frutas",icon:"🍎",color:"#F7C948",items:[
    {es:"Manzana",en:"apple",wiki:"Apple"},{es:"Plátano",en:"banana",wiki:"Banana"},
    {es:"Naranja",en:"orange",wiki:"Orange_(fruit)"},{es:"Fresa",en:"strawberry",wiki:"Strawberry"},
    {es:"Uva",en:"grape",wiki:"Grape"},{es:"Sandía",en:"watermelon",wiki:"Watermelon"},
    {es:"Piña",en:"pineapple",wiki:"Pineapple"},{es:"Mango",en:"mango",wiki:"Mango"},
    {es:"Pera",en:"pear",wiki:"Pear"},{es:"Limón",en:"lemon",wiki:"Lemon"},
    {es:"Cereza",en:"cherry",wiki:"Cherry"},{es:"Kiwi",en:"kiwi",wiki:"Kiwifruit"},
    {es:"Coco",en:"coconut",wiki:"Coconut"},{es:"Durazno",en:"peach",wiki:"Peach"},
    {es:"Papaya",en:"papaya",wiki:"Papaya"}
  ]},
  colores:{label:"Colores",icon:"🎨",color:"#D45FBF",items:[
    {es:"Rojo",en:"red",swatch:"#E53935"},{es:"Azul",en:"blue",swatch:"#1E88E5"},
    {es:"Verde",en:"green",swatch:"#43A047"},{es:"Amarillo",en:"yellow",swatch:"#FDD835"},
    {es:"Naranja",en:"orange",swatch:"#FB8C00"},{es:"Morado",en:"purple",swatch:"#8E24AA"},
    {es:"Rosa",en:"pink",swatch:"#F06292"},{es:"Negro",en:"black",swatch:"#212121"},
    {es:"Blanco",en:"white",swatch:"#F5F5F5",border:true},{es:"Gris",en:"gray",swatch:"#757575"},
    {es:"Marrón",en:"brown",swatch:"#6D4C41"},{es:"Turquesa",en:"turquoise",swatch:"#00BCD4"},
    {es:"Dorado",en:"golden",swatch:"#FFD600"},{es:"Plateado",en:"silver",swatch:"#B0BEC5"},
    {es:"Celeste",en:"sky blue",swatch:"#81D4FA"},{es:"Violeta",en:"violet",swatch:"#7E57C2"},
    {es:"Lima",en:"lime",swatch:"#AEEA00"},{es:"Coral",en:"coral",swatch:"#FF7043"},
    {es:"Índigo",en:"indigo",swatch:"#3949AB"},{es:"Magenta",en:"magenta",swatch:"#D81B60"},
    {es:"Cian",en:"cyan",swatch:"#00ACC1"},{es:"Salmón",en:"salmon",swatch:"#FF8A65"},
    {es:"Esmeralda",en:"emerald",swatch:"#00C853"},{es:"Lavanda",en:"lavender",swatch:"#CE93D8"},
    {es:"Terracota",en:"terracotta",swatch:"#BF5B3D"},{es:"Menta",en:"mint",swatch:"#A5D6A7"},
    {es:"Granate",en:"maroon",swatch:"#880E4F"},{es:"Beige",en:"beige",swatch:"#F5DEB3"},
    {es:"Carmesí",en:"crimson",swatch:"#B71C1C"},{es:"Oliva",en:"olive",swatch:"#827717"}
  ]},
  numeros:{label:"Números",icon:"🔢",color:"#2196C0",items:[
    {es:"Uno",en:"one",numeral:"1"},{es:"Dos",en:"two",numeral:"2"},
    {es:"Tres",en:"three",numeral:"3"},{es:"Cuatro",en:"four",numeral:"4"},
    {es:"Cinco",en:"five",numeral:"5"},{es:"Seis",en:"six",numeral:"6"},
    {es:"Siete",en:"seven",numeral:"7"},{es:"Ocho",en:"eight",numeral:"8"},
    {es:"Nueve",en:"nine",numeral:"9"},{es:"Diez",en:"ten",numeral:"10"},
    {es:"Once",en:"eleven",numeral:"11"},{es:"Doce",en:"twelve",numeral:"12"},
    {es:"Trece",en:"thirteen",numeral:"13"},{es:"Catorce",en:"fourteen",numeral:"14"},
    {es:"Quince",en:"fifteen",numeral:"15"},{es:"Veinte",en:"twenty",numeral:"20"},
    {es:"Treinta",en:"thirty",numeral:"30"},{es:"Cuarenta",en:"forty",numeral:"40"},
    {es:"Cincuenta",en:"fifty",numeral:"50"},{es:"Cien",en:"hundred",numeral:"100"},
    {es:"Cero",en:"zero",numeral:"0"},{es:"Mil",en:"thousand",numeral:"1K"},
    {es:"Primero",en:"first",numeral:"1°"},{es:"Segundo",en:"second",numeral:"2°"},
    {es:"Tercero",en:"third",numeral:"3°"},{es:"Mitad",en:"half",numeral:"½"},
    {es:"Doble",en:"double",numeral:"×2"},{es:"Triple",en:"triple",numeral:"×3"},
    {es:"Par",en:"even",numeral:"2,4"},{es:"Impar",en:"odd",numeral:"1,3"}
  ]},
  formas:{label:"Formas",icon:"🔷",color:"#FF8F00",items:[
    {es:"Círculo",en:"circle",shape:"circle"},{es:"Cuadrado",en:"square",shape:"square"},
    {es:"Triángulo",en:"triangle",shape:"triangle"},{es:"Rectángulo",en:"rectangle",shape:"rectangle"},
    {es:"Estrella",en:"star",shape:"star"},{es:"Corazón",en:"heart",shape:"heart"},
    {es:"Rombo",en:"diamond",shape:"diamond"},{es:"Óvalo",en:"oval",shape:"oval"},
    {es:"Pentágono",en:"pentagon",shape:"pentagon"},{es:"Hexágono",en:"hexagon",shape:"hexagon"},
    {es:"Octágono",en:"octagon",shape:"octagon"},{es:"Cruz",en:"cross",shape:"cross"},
    {es:"Flecha",en:"arrow",shape:"arrow"},{es:"Luna",en:"moon",shape:"moon"},
    {es:"Espiral",en:"spiral",shape:"spiral"},{es:"Trapecio",en:"trapezoid",shape:"trapezoid"},
    {es:"Semicírculo",en:"semicircle",shape:"semicircle"},{es:"Cubo",en:"cube",shape:"cube"},
    {es:"Esfera",en:"sphere",shape:"sphere"},{es:"Pirámide",en:"pyramid",shape:"pyramid"},
    {es:"Cilindro",en:"cylinder",shape:"cylinder"},{es:"Cono",en:"cone",shape:"cone"},
    {es:"Arco",en:"arc",shape:"arc"},{es:"Zigzag",en:"zigzag",shape:"zigzag"},
    {es:"Ola",en:"wave",shape:"wave"},{es:"Nube",en:"cloud",shape:"cloud"},
    {es:"Rayo",en:"lightning",shape:"lightning"},{es:"Anillo",en:"ring",shape:"ring"},
    {es:"Panal",en:"honeycomb",shape:"honeycomb"},{es:"Espejo",en:"mirror shape",shape:"mirror"}
  ]},
  transporte:{label:"Transporte",icon:"🚗",color:"#E53935",items:[
    {es:"Carro",en:"car",wiki:"Car"},{es:"Autobús",en:"bus",wiki:"Bus"},
    {es:"Tren",en:"train",wiki:"Train"},{es:"Avión",en:"airplane",wiki:"Airplane"},
    {es:"Barco",en:"ship",wiki:"Ship"},{es:"Bicicleta",en:"bicycle",wiki:"Bicycle"},
    {es:"Motocicleta",en:"motorcycle",wiki:"Motorcycle"},{es:"Helicóptero",en:"helicopter",wiki:"Helicopter"},
    {es:"Submarino",en:"submarine",wiki:"Submarine"},{es:"Cohete",en:"rocket",wiki:"Rocket"},
    {es:"Taxi",en:"taxi",wiki:"Taxi"},{es:"Camión",en:"truck",wiki:"Truck"},
    {es:"Tractor",en:"tractor",wiki:"Tractor"},{es:"Ambulancia",en:"ambulance",wiki:"Ambulance"},
    {es:"Bombero",en:"fire truck",wiki:"Fire_engine"},{es:"Tranvía",en:"tram",wiki:"Tram"},
    {es:"Ferry",en:"ferry",wiki:"Ferry"},{es:"Velero",en:"sailboat",wiki:"Sailboat"},
    {es:"Kayak",en:"kayak",wiki:"Kayak"},{es:"Paracaídas",en:"parachute",wiki:"Parachute"},
    {es:"Globo aerostático",en:"hot air balloon",wiki:"Hot_air_balloon"},
    {es:"Teleférico",en:"cable car",wiki:"Cable_car_(railway)"},
    {es:"Patineta",en:"skateboard",wiki:"Skateboard"},{es:"Monopatín",en:"scooter",wiki:"Kick_scooter"},
    {es:"Trineo",en:"sled",wiki:"Sled"},{es:"Canoa",en:"canoe",wiki:"Canoe"},
    {es:"Metro",en:"subway",wiki:"Rapid_transit"},{es:"Zeppelin",en:"zeppelin",wiki:"Zeppelin"},
    {es:"Grúa",en:"crane",wiki:"Crane_(machine)"},{es:"Excavadora",en:"excavator",wiki:"Excavator"}
  ]}
};

const ANIM_MAP={
  Loro:"fly",Mariposa:"fly",Águila:"fly",Colibrí:"fly",Pato:"fly",Pingüino:"wiggle",
  Abeja:"fly",Murciélago:"fly",Flamenco:"wiggle",Búho:"wiggle",
  Pelota:"bounce",Conejo:"bounce",Canguro:"bounce",Rana:"bounce",Perro:"bounce",
  Gato:"wiggle",Zorro:"wiggle",Tigre:"wiggle",León:"wiggle",Lobo:"wiggle",
  Delfín:"swim",Tiburón:"swim",Ballena:"swim",Pulpo:"swim",
  Bicicleta:"spin",Carro:"swim",Tren:"swim",Avión:"fly",Cohete:"fly",
  Helicóptero:"fly",Patineta:"swim",Globo:"fly",Paraguas:"grow",
  Estrella:"spin",Corazón:"pulse",Espiral:"spin",Rayo:"shake",
  Manzana:"bounce",Uva:"bounce",Fresa:"bounce",
  Elefante:"shake",Hipopótamo:"shake",Gorila:"shake",Oso:"shake",
  Serpiente:"swim",Cocodrilo:"swim",Tortuga:"swim",
};
function getAnim(w){return ANIM_MAP[w]||'bounce';}
function getAnim(w){return ANIM_MAP[w]||'bounce';}

const FALLBACKS={
  Silla:"🪑",Mesa:"🪵",Cama:"🛏️",Puerta:"🚪",Ventana:"🪟",Libro:"📚",Lápiz:"✏️",
  Zapato:"👟",Sombrero:"🎩",Reloj:"⏰",Mochila:"🎒",Taza:"☕",Cuchara:"🥄",
  Pelota:"⚽",Tijeras:"✂️",Teléfono:"📱",Lámpara:"💡",Espejo:"🪞",Llave:"🗝️",
  Botella:"🍶",Globo:"🎈",Paraguas:"☂️",Vela:"🕯️",Guitarra:"🎸",Bicicleta:"🚲",
  Avión:"✈️",Tren:"🚂",Barco:"🚢",Cepillo:"🖌️",Carro:"🚗",
  Perro:"🐶",Gato:"🐱",Elefante:"🐘",León:"🦁",Tigre:"🐯",Jirafa:"🦒",
  Cebra:"🦓",Pingüino:"🐧",Delfín:"🐬",Águila:"🦅",Oso:"🐻",Lobo:"🐺",
  Zorro:"🦊",Conejo:"🐰",Tortuga:"🐢",Cocodrilo:"🐊",Mariposa:"🦋",Abeja:"🐝",
  Pulpo:"🐙",Tiburón:"🦈",Caballo:"🐴",Vaca:"🐄",Cerdo:"🐷",Pato:"🦆",
  Gallina:"🐔",Camello:"🐪",Hipopótamo:"🦛",Loro:"🦜",Panda:"🐼",Koala:"🐨",
  Canguro:"🦘",Rana:"🐸",Serpiente:"🐍",Murciélago:"🦇",Búho:"🦉",Cangrejo:"🦀",
  Ballena:"🐳",Gorila:"🦍",Flamenco:"🦩",Colibrí:"🐦",
  Ojo:"👁️",Nariz:"👃",Boca:"👄",Oreja:"👂",Mano:"✋",Pie:"🦶",Brazo:"💪",
  Pierna:"🦵",Cabeza:"🗣️",Diente:"🦷",Cabello:"💇",Rodilla:"🦵",Codo:"💪",
  Hombro:"🤷",Dedo:"☝️",Uña:"💅",Espalda:"🧍",Cuello:"🦒",Mejilla:"😊",Frente:"😮",
  Manzana:"🍎",Plátano:"🍌",Naranja:"🍊",Fresa:"🍓",Uva:"🍇",Sandía:"🍉",
  Piña:"🍍",Mango:"🥭",Pera:"🍐",Limón:"🍋",Cereza:"🍒",Kiwi:"🥝",
  Coco:"🥥",Durazno:"🍑",Papaya:"🥭",
  Autobús:"🚌",Motocicleta:"🏍️",Helicóptero:"🚁",Submarino:"🚤",Cohete:"🚀",
  Taxi:"🚕",Camión:"🚚",Tractor:"🚜",Ambulancia:"🚑",Bombero:"🚒",
  Tranvía:"🚋",Ferry:"⛴️",Velero:"⛵",Kayak:"🚣",Paracaídas:"🪂",
  "Globo aerostático":"🎈",Teleférico:"🚡",Patineta:"🛹",Monopatín:"🛴",
  Trineo:"🛷",Canoa:"🚣",Metro:"🚇",Zeppelin:"🛸",Grúa:"🏗️",Excavadora:"🚧"
};

const SYLLS={
  Silla:["Si","lla"],Mesa:["Me","sa"],Cama:["Ca","ma"],Puerta:["Puer","ta"],
  Ventana:["Ven","ta","na"],Libro:["Li","bro"],Lápiz:["Lá","piz"],Zapato:["Za","pa","to"],
  Sombrero:["Som","bre","ro"],Reloj:["Re","loj"],Mochila:["Mo","chi","la"],Taza:["Ta","za"],
  Cuchara:["Cu","cha","ra"],Pelota:["Pe","lo","ta"],Tijeras:["Ti","je","ras"],
  Teléfono:["Te","lé","fo","no"],Lámpara:["Lám","pa","ra"],Espejo:["Es","pe","jo"],
  Llave:["Lla","ve"],Botella:["Bo","te","lla"],Globo:["Glo","bo"],Paraguas:["Pa","ra","guas"],
  Vela:["Ve","la"],Guitarra:["Gui","ta","rra"],Bicicleta:["Bi","ci","cle","ta"],
  Avión:["A","vión"],Tren:["Tren"],Barco:["Bar","co"],Cepillo:["Ce","pi","llo"],Carro:["Ca","rro"],
  Perro:["Pe","rro"],Gato:["Ga","to"],Elefante:["E","le","fan","te"],León:["León"],
  Tigre:["Ti","gre"],Jirafa:["Ji","ra","fa"],Cebra:["Ce","bra"],Pingüino:["Pin","güi","no"],
  Delfín:["Del","fín"],Águila:["Á","gui","la"],Oso:["O","so"],Lobo:["Lo","bo"],
  Zorro:["Zo","rro"],Conejo:["Co","ne","jo"],Tortuga:["Tor","tu","ga"],
  Cocodrilo:["Co","co","dri","lo"],Mariposa:["Ma","ri","po","sa"],Abeja:["A","be","ja"],
  Pulpo:["Pul","po"],Tiburón:["Ti","bu","rón"],Caballo:["Ca","ba","llo"],
  Vaca:["Va","ca"],Cerdo:["Cer","do"],Pato:["Pa","to"],Gallina:["Ga","lli","na"],
  Camello:["Ca","me","llo"],Hipopótamo:["Hi","po","pó","ta","mo"],Loro:["Lo","ro"],
  Panda:["Pan","da"],Koala:["Ko","a","la"],Canguro:["Can","gu","ro"],Rana:["Ra","na"],
  Serpiente:["Ser","pien","te"],Murciélago:["Mur","cié","la","go"],Búho:["Bú","ho"],
  Cangrejo:["Can","gre","jo"],Ballena:["Ba","lle","na"],Gorila:["Go","ri","la"],
  Flamenco:["Fla","men","co"],Colibrí:["Co","li","brí"],
  Ojo:["O","jo"],Nariz:["Na","riz"],Boca:["Bo","ca"],Oreja:["O","re","ja"],
  Mano:["Ma","no"],Pie:["Pie"],Brazo:["Bra","zo"],Pierna:["Pier","na"],
  Cabeza:["Ca","be","za"],Diente:["Dien","te"],Cabello:["Ca","be","llo"],
  Rodilla:["Ro","di","lla"],Codo:["Co","do"],Hombro:["Hom","bro"],Dedo:["De","do"],
  Espalda:["Es","pal","da"],Cuello:["Cue","llo"],Mejilla:["Me","ji","lla"],Frente:["Fren","te"],
  Manzana:["Man","za","na"],Plátano:["Plá","ta","no"],Naranja:["Na","ran","ja"],
  Fresa:["Fre","sa"],Uva:["U","va"],Sandía:["San","dí","a"],Piña:["Pi","ña"],
  Mango:["Man","go"],Pera:["Pe","ra"],Limón:["Li","món"],Cereza:["Ce","re","za"],
  Kiwi:["Ki","wi"],Coco:["Co","co"],Durazno:["Du","raz","no"],Papaya:["Pa","pa","ya"],
  Rojo:["Ro","jo"],Azul:["A","zul"],Verde:["Ver","de"],Amarillo:["A","ma","ri","llo"],
  Morado:["Mo","ra","do"],Rosa:["Ro","sa"],Negro:["Ne","gro"],Blanco:["Blan","co"],
  Turquesa:["Tur","que","sa"],Dorado:["Do","ra","do"],Plateado:["Pla","tea","do"],
  Celeste:["Ce","les","te"],Violeta:["Vio","le","ta"],Magenta:["Ma","gen","ta"],
  Índigo:["Ín","di","go"],Salmón:["Sal","món"],Lavanda:["La","van","da"],
  Terracota:["Te","rra","co","ta"],Menta:["Men","ta"],Granate:["Gra","na","te"],
  Uno:["U","no"],Dos:["Dos"],Tres:["Tres"],Cuatro:["Cua","tro"],Cinco:["Cin","co"],
  Siete:["Sie","te"],Ocho:["O","cho"],Nueve:["Nue","ve"],Once:["On","ce"],
  Doce:["Do","ce"],Trece:["Tre","ce"],Catorce:["Ca","tor","ce"],Quince:["Quin","ce"],
  Veinte:["Vein","te"],Treinta:["Trein","ta"],Cuarenta:["Cua","ren","ta"],
  Cincuenta:["Cin","cuen","ta"],Primero:["Pri","me","ro"],Segundo:["Se","gun","do"],
  Tercero:["Ter","ce","ro"],Mitad:["Mi","tad"],Doble:["Do","ble"],Triple:["Tri","ple"],Impar:["Im","par"],
  Círculo:["Cír","cu","lo"],Cuadrado:["Cua","dra","do"],Triángulo:["Trián","gu","lo"],
  Rectángulo:["Rec","tán","gu","lo"],Estrella:["Es","tre","lla"],Corazón:["Co","ra","zón"],
  Rombo:["Rom","bo"],Óvalo:["Ó","va","lo"],Pentágono:["Pen","tá","go","no"],
  Hexágono:["He","xá","go","no"],Octágono:["Oc","tá","go","no"],Flecha:["Fle","cha"],
  Luna:["Lu","na"],Espiral:["Es","pi","ral"],Trapecio:["Tra","pe","cio"],
  Semicírculo:["Se","mi","cír","cu","lo"],Cubo:["Cu","bo"],Esfera:["Es","fe","ra"],
  Pirámide:["Pi","rá","mi","de"],Cilindro:["Ci","lin","dro"],Cono:["Co","no"],
  Zigzag:["Zig","zag"],Nube:["Nu","be"],Rayo:["Ra","yo"],Anillo:["A","ni","llo"],
  Panal:["Pa","nal"],Autobús:["Au","to","bús"],Motocicleta:["Mo","to","ci","cle","ta"],
  Helicóptero:["He","li","cóp","te","ro"],Submarino:["Sub","ma","ri","no"],
  Cohete:["Co","he","te"],Camión:["Ca","mión"],Tractor:["Trac","tor"],
  Ambulancia:["Am","bu","lan","cia"],Tranvía:["Tran","ví","a"],
  Velero:["Ve","le","ro"],Kayak:["Ka","yak"],Paracaídas:["Pa","ra","caí","das"],
  Teleférico:["Te","le","fé","ri","co"],Patineta:["Pa","ti","ne","ta"],
  Monopatín:["Mo","no","pa","tín"],Trineo:["Tri","neo"],Canoa:["Ca","no","a"],Metro:["Me","tro"]
};

function drawShape(shape,color){
  const c=color||'#FF8F00';
  const shapes={
    circle:`<ellipse cx="110" cy="110" rx="82" ry="82" fill="${c}" opacity="0.85"/>`,
    square:`<rect x="28" y="28" width="164" height="164" rx="12" fill="${c}" opacity="0.85"/>`,
    triangle:`<polygon points="110,18 202,192 18,192" fill="${c}" opacity="0.85"/>`,
    rectangle:`<rect x="12" y="55" width="196" height="110" rx="10" fill="${c}" opacity="0.85"/>`,
    star:`<polygon points="110,12 132,80 202,80 147,122 167,192 110,152 53,192 73,122 18,80 88,80" fill="${c}" opacity="0.85"/>`,
    heart:`<path d="M110,178C58,130 18,98 18,62C18,38 38,18 62,18C82,18 98,32 110,48C122,32 138,18 158,18C182,18 202,38 202,62C202,98 162,130 110,178Z" fill="${c}" opacity="0.85"/>`,
    diamond:`<polygon points="110,8 204,110 110,212 16,110" fill="${c}" opacity="0.85"/>`,
    oval:`<ellipse cx="110" cy="110" rx="92" ry="56" fill="${c}" opacity="0.85"/>`,
    pentagon:`<polygon points="110,14 202,78 168,192 52,192 18,78" fill="${c}" opacity="0.85"/>`,
    hexagon:`<polygon points="110,8 192,54 192,146 110,192 28,146 28,54" fill="${c}" opacity="0.85"/>`,
    octagon:`<polygon points="68,8 152,8 202,58 202,152 152,202 68,202 18,152 18,58" fill="${c}" opacity="0.85"/>`,
    cross:`<path d="M78,8H142V78H212V142H142V212H78V142H8V78H78Z" fill="${c}" opacity="0.85"/>`,
    arrow:`<polygon points="110,8 202,100 152,100 152,202 68,202 68,100 18,100" fill="${c}" opacity="0.85"/>`,
    moon:`<path d="M110,18A82,82 0 1,0 110,202A52,52 0 1,1 110,18Z" fill="${c}" opacity="0.85"/>`,
    spiral:`<path d="M110,110 m0,-62 a62,62 0 1,1 -1,0 m1,62 a46,46 0 1,0 1,0 m-1,-46 a30,30 0 1,1 -1,0" fill="none" stroke="${c}" stroke-width="14" opacity="0.85"/>`,
    trapezoid:`<polygon points="38,172 182,172 202,48 18,48" fill="${c}" opacity="0.85"/>`,
    semicircle:`<path d="M18,110A92,92 0 0,1 202,110Z" fill="${c}" opacity="0.85"/>`,
    cube:`<polygon points="110,18 192,64 192,156 110,202 28,156 28,64" fill="${c}" opacity="0.68"/><polygon points="110,18 192,64 110,110 28,64" fill="${c}" opacity="0.9"/><polygon points="192,64 192,156 110,202 110,110" fill="${c}" opacity="0.56"/>`,
    sphere:`<ellipse cx="110" cy="110" rx="87" ry="87" fill="${c}" opacity="0.82"/>`,
    pyramid:`<polygon points="110,12 196,192 24,192" fill="${c}" opacity="0.8"/><polygon points="110,12 196,192 110,142" fill="${c}" opacity="0.58"/>`,
    cylinder:`<ellipse cx="110" cy="54" rx="76" ry="26" fill="${c}" opacity="0.9"/><rect x="34" y="54" width="152" height="120" fill="${c}" opacity="0.74"/><ellipse cx="110" cy="174" rx="76" ry="26" fill="${c}" opacity="0.85"/>`,
    cone:`<polygon points="110,12 196,192 24,192" fill="${c}" opacity="0.85"/><ellipse cx="110" cy="192" rx="86" ry="23" fill="${c}" opacity="0.68"/>`,
    arc:`<path d="M24,172 A96,96 0 0,1 196,172" fill="none" stroke="${c}" stroke-width="22" stroke-linecap="round" opacity="0.85"/>`,
    zigzag:`<polyline points="12,68 52,152 92,68 132,152 172,68 212,152" fill="none" stroke="${c}" stroke-width="16" stroke-linecap="round" stroke-linejoin="round" opacity="0.85"/>`,
    wave:`<path d="M12,110 C44,58 76,162 110,110 C144,58 176,162 208,110" fill="none" stroke="${c}" stroke-width="18" stroke-linecap="round" opacity="0.85"/>`,
    cloud:`<ellipse cx="78" cy="132" rx="56" ry="46" fill="${c}" opacity="0.85"/><ellipse cx="142" cy="132" rx="56" ry="46" fill="${c}" opacity="0.85"/><ellipse cx="110" cy="98" rx="56" ry="52" fill="${c}" opacity="0.85"/>`,
    lightning:`<polygon points="132,8 78,112 116,112 88,212 162,88 122,88 148,8" fill="${c}" opacity="0.85"/>`,
    ring:`<circle cx="110" cy="110" r="82" fill="none" stroke="${c}" stroke-width="30" opacity="0.85"/>`,
    honeycomb:`<polygon points="78,18 142,18 172,74 142,130 78,130 48,74" fill="${c}" opacity="0.6"/><polygon points="142,18 206,18 224,74 206,130 142,130 120,74" fill="${c}" opacity="0.4"/><polygon points="78,130 142,130 172,186 142,220 78,220 48,186" fill="${c}" opacity="0.5"/>`,
    mirror:`<rect x="53" y="18" width="104" height="184" rx="52" fill="${c}" opacity="0.85"/>`
  };
  return `<svg viewBox="0 0 220 220" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%;padding:18px">${shapes[shape]||shapes.circle}</svg>`;
}

// ── NEW CATEGORIES ────────────────────────────────────────────────────────────
const CATS_EXTRA = {
  vegetales:{label:"Vegetales",icon:"🥦",color:"#66BB6A",items:[
    {es:"Zanahoria",en:"carrot",wiki:"Carrot"},{es:"Brócoli",en:"broccoli",wiki:"Broccoli"},
    {es:"Tomate",en:"tomato",wiki:"Tomato"},{es:"Lechuga",en:"lettuce",wiki:"Lettuce"},
    {es:"Papa",en:"potato",wiki:"Potato"},{es:"Cebolla",en:"onion",wiki:"Onion"},
    {es:"Pepino",en:"cucumber",wiki:"Cucumber"},{es:"Maíz",en:"corn",wiki:"Maize"},
    {es:"Espinaca",en:"spinach",wiki:"Spinach"},{es:"Calabaza",en:"pumpkin",wiki:"Pumpkin"},
    {es:"Berenjena",en:"eggplant",wiki:"Eggplant"},{es:"Coliflor",en:"cauliflower",wiki:"Cauliflower"},
    {es:"Apio",en:"celery",wiki:"Celery"},{es:"Pimiento",en:"pepper",wiki:"Capsicum"},
    {es:"Champiñón",en:"mushroom",wiki:"Mushroom"},{es:"Arveja",en:"pea",wiki:"Pea"},
    {es:"Rábano",en:"radish",wiki:"Radish"},{es:"Alcachofa",en:"artichoke",wiki:"Artichoke"},
    {es:"Espárrago",en:"asparagus",wiki:"Asparagus"},{es:"Nabo",en:"turnip",wiki:"Turnip"},
    {es:"Puerro",en:"leek",wiki:"Leek"},{es:"Remolacha",en:"beet",wiki:"Beetroot"},
    {es:"Jengibre",en:"ginger",wiki:"Ginger"},{es:"Ajo",en:"garlic",wiki:"Garlic"},
    {es:"Choclo",en:"sweet corn",wiki:"Sweet_corn"}
  ]},
  ropa:{label:"Ropa",icon:"👕",color:"#AB47BC",items:[
    {es:"Camiseta",en:"t-shirt",wiki:"T-shirt"},{es:"Pantalón",en:"pants",wiki:"Trousers"},
    {es:"Vestido",en:"dress",wiki:"Dress"},{es:"Zapatos",en:"shoes",wiki:"Shoe"},
    {es:"Calcetines",en:"socks",wiki:"Sock"},{es:"Bufanda",en:"scarf",wiki:"Scarf"},
    {es:"Guantes",en:"gloves",wiki:"Glove"},{es:"Abrigo",en:"coat",wiki:"Coat_(clothing)"},
    {es:"Pijama",en:"pajamas",wiki:"Pajamas"},{es:"Cinturón",en:"belt",wiki:"Belt_(clothing)"},
    {es:"Gorra",en:"cap",wiki:"Cap_(clothing)"},{es:"Suéter",en:"sweater",wiki:"Sweater"},
    {es:"Falda",en:"skirt",wiki:"Skirt"},{es:"Chaqueta",en:"jacket",wiki:"Jacket"},
    {es:"Corbata",en:"tie",wiki:"Necktie"},{es:"Sandalias",en:"sandals",wiki:"Sandal"},
    {es:"Botas",en:"boots",wiki:"Boot"},{es:"Bolso",en:"bag",wiki:"Handbag"},
    {es:"Delantal",en:"apron",wiki:"Apron"},{es:"Capa",en:"cape",wiki:"Cape_(clothing)"},
    {es:"Overol",en:"overalls",wiki:"Overall"},{es:"Bikini",en:"bikini",wiki:"Bikini"},
    {es:"Pañuelo",en:"handkerchief",wiki:"Handkerchief"},
    {es:"Sombrero",en:"hat",wiki:"Hat"},{es:"Mochila",en:"backpack",wiki:"Backpack"}
  ]},
  profesiones:{label:"Profesiones",icon:"👨‍⚕️",color:"#FF7043",items:[
    {es:"Doctor",en:"doctor",wiki:"Physician"},{es:"Maestro",en:"teacher",wiki:"Teacher"},
    {es:"Bombero",en:"firefighter",wiki:"Firefighter"},{es:"Policía",en:"police officer",wiki:"Police"},
    {es:"Chef",en:"chef",wiki:"Chef"},{es:"Piloto",en:"pilot",wiki:"Aviator"},
    {es:"Astronauta",en:"astronaut",wiki:"Astronaut"},{es:"Artista",en:"artist",wiki:"Artist"},
    {es:"Músico",en:"musician",wiki:"Musician"},{es:"Veterinario",en:"veterinarian",wiki:"Veterinarian"},
    {es:"Ingeniero",en:"engineer",wiki:"Engineer"},{es:"Agricultor",en:"farmer",wiki:"Farmer"},
    {es:"Dentista",en:"dentist",wiki:"Dentist"},{es:"Enfermero",en:"nurse",wiki:"Nurse"},
    {es:"Carpintero",en:"carpenter",wiki:"Carpenter"},{es:"Científico",en:"scientist",wiki:"Scientist"},
    {es:"Arquitecto",en:"architect",wiki:"Architect"},{es:"Fotógrafo",en:"photographer",wiki:"Photographer"},
    {es:"Panadero",en:"baker",wiki:"Baker"},{es:"Jardinero",en:"gardener",wiki:"Gardening"},
    {es:"Escritor",en:"writer",wiki:"Author"},{es:"Actor",en:"actor",wiki:"Actor"},
    {es:"Cantante",en:"singer",wiki:"Singer"},{es:"Bailarín",en:"dancer",wiki:"Dance"},
    {es:"Nadador",en:"swimmer",wiki:"Swimming_(sport)"}
  ]},
  emociones:{label:"Emociones",icon:"😊",color:"#FFA726",items:[
    {es:"Feliz",en:"happy",swatch:"#FFD700",emoji:"😄"},
    {es:"Triste",en:"sad",swatch:"#5B8DD9",emoji:"😢"},
    {es:"Enojado",en:"angry",swatch:"#E53935",emoji:"😠"},
    {es:"Sorprendido",en:"surprised",swatch:"#AB47BC",emoji:"😲"},
    {es:"Asustado",en:"scared",swatch:"#546E7A",emoji:"😨"},
    {es:"Enamorado",en:"in love",swatch:"#E91E63",emoji:"😍"},
    {es:"Cansado",en:"tired",swatch:"#78909C",emoji:"😴"},
    {es:"Emocionado",en:"excited",swatch:"#FF9800",emoji:"🤩"},
    {es:"Aburrido",en:"bored",swatch:"#90A4AE",emoji:"😒"},
    {es:"Orgulloso",en:"proud",swatch:"#7B8FF7",emoji:"😤"},
    {es:"Avergonzado",en:"embarrassed",swatch:"#F48FB1",emoji:"😳"},
    {es:"Confundido",en:"confused",swatch:"#80CBC4",emoji:"😕"},
    {es:"Nervioso",en:"nervous",swatch:"#A5D6A7",emoji:"😰"},
    {es:"Tranquilo",en:"calm",swatch:"#80DEEA",emoji:"😌"},
    {es:"Curioso",en:"curious",swatch:"#FFCC80",emoji:"🤔"},
    {es:"Valiente",en:"brave",swatch:"#EF9A9A",emoji:"💪"},
    {es:"Tímido",en:"shy",swatch:"#CE93D8",emoji:"🙈"},
    {es:"Celoso",en:"jealous",swatch:"#A5D6A7",emoji:"😒"},
    {es:"Agradecido",en:"grateful",swatch:"#FFF59D",emoji:"🙏"},
    {es:"Esperanzado",en:"hopeful",swatch:"#B3E5FC",emoji:"🌟"},
    {es:"Divertido",en:"amused",swatch:"#FFAB91",emoji:"😂"},
    {es:"Asombrado",en:"amazed",swatch:"#E1BEE7",emoji:"🤯"},
    {es:"Contento",en:"content",swatch:"#C8E6C9",emoji:"😊"},
    {es:"Frustrado",en:"frustrated",swatch:"#FFCDD2",emoji:"😤"},
    {es:"Alegre",en:"joyful",swatch:"#DCEDC8",emoji:"🤗"}
  ]}
};

// Merge into CATS
Object.assign(CATS, CATS_EXTRA);

// Extra syllables for new categories
const SYLLS_EXTRA = {
  Zanahoria:["Za","na","ho","ria"],Brócoli:["Bró","co","li"],Tomate:["To","ma","te"],
  Lechuga:["Le","chu","ga"],Papa:["Pa","pa"],Cebolla:["Ce","bo","lla"],
  Pepino:["Pe","pi","no"],Espinaca:["Es","pi","na","ca"],Calabaza:["Ca","la","ba","za"],
  Berenjena:["Be","ren","je","na"],Coliflor:["Co","li","flor"],Remolacha:["Re","mo","la","cha"],
  Pimiento:["Pi","mien","to"],Champiñón:["Cham","pi","ñón"],Espárrago:["Es","pá","rra","go"],
  Alcachofa:["Al","ca","cho","fa"],Rábano:["Rá","ba","no"],Puerro:["Pue","rro"],
  Camiseta:["Ca","mi","se","ta"],Pantalón:["Pan","ta","lón"],Vestido:["Ves","ti","do"],
  Calcetines:["Cal","ce","ti","nes"],Bufanda:["Bu","fan","da"],Pijama:["Pi","ja","ma"],
  Cinturón:["Cin","tu","rón"],Suéter:["Sué","ter"],Chaqueta:["Cha","que","ta"],
  Corbata:["Cor","ba","ta"],Sandalias:["San","da","lias"],Delantal:["De","lan","tal"],
  Overol:["O","ve","rol"],Doctor:["Doc","tor"],Maestro:["Maes","tro"],
  Policía:["Po","li","cí","a"],Piloto:["Pi","lo","to"],Astronauta:["As","tro","nau","ta"],
  Artista:["Ar","tis","ta"],Músico:["Mú","si","co"],Veterinario:["Ve","te","ri","na","rio"],
  Ingeniero:["In","ge","nie","ro"],Agricultor:["A","gri","cul","tor"],
  Dentista:["Den","tis","ta"],Enfermero:["En","fer","me","ro"],
  Carpintero:["Car","pin","te","ro"],Científico:["Cien","tí","fi","co"],
  Arquitecto:["Ar","qui","tec","to"],Fotógrafo:["Fo","tó","gra","fo"],
  Panadero:["Pa","na","de","ro"],Jardinero:["Jar","di","ne","ro"],
  Escritor:["Es","cri","tor"],Cantante:["Can","tan","te"],Bailarín:["Bai","la","rín"],
  Nadador:["Na","da","dor"],Feliz:["Fe","liz"],Triste:["Tris","te"],
  Enojado:["E","no","ja","do"],Sorprendido:["Sor","pren","di","do"],
  Asustado:["A","sus","ta","do"],Enamorado:["E","na","mo","ra","do"],
  Cansado:["Can","sa","do"],Emocionado:["E","mo","cio","na","do"],
  Aburrido:["A","bu","rri","do"],Orgulloso:["Or","gu","llo","so"],
  Avergonzado:["A","ver","gon","za","do"],Confundido:["Con","fun","di","do"],
  Nervioso:["Ner","vio","so"],Tranquilo:["Tran","qui","lo"],Curioso:["Cu","rio","so"],
  Valiente:["Va","lien","te"],Tímido:["Tí","mi","do"],Agradecido:["A","gra","de","ci","do"],
  Esperanzado:["Es","pe","ran","za","do"],Divertido:["Di","ver","ti","do"],
  Asombrado:["A","som","bra","do"],Contento:["Con","ten","to"],
  Frustrado:["Frus","tra","do"],Alegre:["A","le","gre"]
};
Object.assign(SYLLS, SYLLS_EXTRA);
